CREATE DATABASE Week4 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE Week4;

CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(20) NOT NULL UNIQUE,
    hashedPassword VARCHAR(300) NOT NULL,
    displayName VARCHAR(35) NOT NULL UNIQUE,
    selfInformation VARCHAR(330),
    profileImage VARCHAR(100) NOT NULL DEFAULT "default.svg",
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    isAdmin TINYINT NOT NULL DEFAULT 0,
    isDeleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE Posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    authorId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDeleted TINYINT NOT NULL DEFAULT 0,
  
    FOREIGN KEY (authorId) REFERENCES Users (id) ON DELETE CASCADE
);

CREATE TABLE Tags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tagId INT NOT NULL,
    tag VARCHAR(100) NOT NULL
);

CREATE TABLE PostTags (
    postId INT NOT NULL,
    tagId INT NOT NULL,

    FOREIGN KEY (postId) REFERENCES Posts (id) ON DELETE CASCADE,
    FOREIGN KEY (tagId) REFERENCES Tags (id) ON DELETE CASCADE,
    
    PRIMARY KEY (postId, tagId)
);

CREATE TABLE Stars (
    followerId INT,
    followingId INT,

    FOREIGN KEY (followerId) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (followingId) REFERENCES Users(id) ON DELETE CASCADE,

    PRIMARY KEY (followerId, followingId)
);

CREATE TABLE Comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    postId INT NOT NULL,
    userId INT NOT NULL,
    comment TEXT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    parentCommentId INT DEFAULT NULL,

    FOREIGN KEY (postId) REFERENCES Posts(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);
